version: "3.6"
services:
  web:
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    image: "${IMAGE_NAME}:${GITHUB_SHA}"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    container_name: intronet-front
    restart: always
    ports:
      - "4000:80"
    networks:
      apps:
    links:
      - db
      - server
    depends_on:
      - db
      - server

  server:
    build:
      context: server
    image: "${IMAGE_NAME_BACKEND}:${GITHUB_SHA}"
    environment:
      - PORT=80
      - DATABASE=http://admin:password@db:5984
    restart: always
    links:
      - db
      - logstash
    depends_on:
      - db
      - logstash
    networks:
      apps:

  db:
    container_name: insomnia_couchdb
    image: couchdb
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    restart: always
    ports:
      - "5984:5984"
    networks:
      apps:
    volumes:
      - couchdb_data:/opt/couchdb/data
      - ./couchdb.ini:/opt/couchdb/etc/local.ini

  elasticsearch:
    image: elasticsearch:7.16.1
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data:rw
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - elastic

  logstash:
    image: logstash:7.16.1
    container_name: logstash
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
      ELASTIC_PASSWORD: ELASTIC_PASSWORD
    volumes:
      - ./.deploy/logstash.config:/usr/share/logstash/pipeline/logstash-nginx.config:ro
    depends_on:
      - elasticsearch
    networks:
      - elastic
      - apps
    command: logstash -f /usr/share/logstash/pipeline/logstash-nginx.config

  kibana:
    image: kibana:7.16.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic
      - apps

volumes:
  couchdb_data:
  elastic_data:

networks:
  elastic:
    driver: bridge
  apps:
    external: true
