name: Docker Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: [self-hosted, acsrv]
    env:
      IMAGE_NAME: intronet-front
      IMAGE_NAME_SERVER: intronet-server
    steps:
      - name: run image
        run: docker-compose up -d
      - name: cleanup docker containers
        run: docker container prune --filter "until=24h" -f
      - name: cleanup docker images
        run: docker image prune -a -f --filter "until=24h"
